name: qwc
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  # firebase
  firebase_auth: ^3.7.0
  firebase_core: ^1.21.1
  firebase_database: ^9.1.3

  # others
  get: ^4.6.5
  shimmer: ^2.0.0
  connectivity_plus: ^2.3.6+1
  google_fonts: ^3.0.1
  another_flushbar: ^1.10.29
  line_awesome_flutter: ^2.0.0
  fl_chart: ^0.55.1
  auto_size_text: ^3.0.0
  popover: ^0.2.6+3
  kumi_popup_window: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
